name: Run Tests
on: [push]

jobs:
  build:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      uses: CultureHQ/actions-bundler@master
      with:
        args: install --jobs 4
    - name: Run Rails-independent specs
      uses: CultureHQ/actions-bundler@master
      with:
        args: exec rspec spec/lib
    - name: Run Rails-dependent specs
      uses: CultureHQ/actions-bundler@master
      env:
        WORKDIR: ./spec/dummy
      with:
        args: exec rspec spec
