name: Run Tests
on: [push]

jobs:
  build:
    name: Run RSpec
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run specs
      run: |
        rspec spec/lib/**/*_spec.rb && cd spec/dummy && rspec spec/**/*_spec.rb
