name: Run Tests
on: [push]

jobs:
  build:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: "2.6.x"
    - name: Install Postgres
      run: apt-get install postgresql-11
    - name: Install dependencies
      run: |
        rm Gemfile.lock
        bundle install
    - name: Run Rails-independent specs
      run: rspec spec/lib
    - name: Run Rails-dependent specs
      working-directory: ./spec/dummy
      run: rspec spec
