name: Tests
on: [push]
jobs:
  build:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: "2.6.x"
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: "11"
    - name: Install dependencies
      run: |
        rm Gemfile.lock
        bundle install
    - name: Create database
      run: rails db:create
    - name: Run Rails-independent specs
      run: rspec spec/lib
    - name: Run Rails-dependent specs
      working-directory: ./spec/dummy
      run: rspec spec
